
package Comerciales;


import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 * Contiene las variables y métodos para la creación y visualización de la segunda
 * ventana del programa, así como la llamada a la siguiente ventana.
 * @author Brais Núñez y Mario Blanco
 */
public class VentanaLogin extends javax.swing.JFrame {
Scanner sc;
Scanner sb;
    File fich;
    public VentanaLogin() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        BotonAcceso = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        etiqueta1 = new javax.swing.JLabel();
        etiqueta2 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 210, 40));

        BotonAcceso.setText("LOGIN");
        BotonAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAccesoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 60, -1));

        etiqueta1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etiqueta1.setForeground(new java.awt.Color(204, 204, 204));
        etiqueta1.setText("USER ID");
        getContentPane().add(etiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 40));

        etiqueta2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etiqueta2.setForeground(new java.awt.Color(204, 204, 204));
        etiqueta2.setText("PASSWORD");
        getContentPane().add(etiqueta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 40));

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/id comercial.jpg"))); // NOI18N
        jLabel1.setText("Log");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
   
    }//GEN-LAST:event_txtPassActionPerformed

    private void BotonAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAccesoActionPerformed
         File usuario  = new File ("usuario1.txt");
         File usuario2 = new File("usuario2.txt");
         boolean stop =false;
         
    try {
       sc = new Scanner(usuario);
       sb = new  Scanner(usuario2);
        
       if(txtUsuario.getText().isEmpty()||txtPass.getPassword().length==0){
       JOptionPane.showMessageDialog(null, "Usuario o contraseña no pueden estar vacíos");
       }else{
        while((sc.hasNext()&&sb.hasNext()&&!stop)){
          if(sc.next().equals(txtUsuario.getText())||sb.next().equals(txtUsuario.getText())){
             if(sc.next().equals(txtPass.getPassword())||sb.next().equals(txtPass.getPassword()))
                  stop=true;
              JOptionPane.showMessageDialog(null,"Bienvenido");
                      
               VentanaElec  otraVent = new VentanaElec();
               otraVent.setVisible(true);
               this.dispose();
          break;
          }else
          stop=true;    
          JOptionPane.showMessageDialog(null,"Usuario o contraseña incorrectos ");
        }
       }
        
    } catch (FileNotFoundException ex) {
        System.out.println("archivo no encontrado"+ex);
    }finally{
        sc.close();
    }
     
    }//GEN-LAST:event_BotonAccesoActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAcceso;
    private javax.swing.JLabel etiqueta1;
    private javax.swing.JLabel etiqueta2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
